spring.application.name=AgxiTopupSimulation
spring.datasource.url=jdbc:mysql://localhost:3306/agxitopupdb
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
g2bulk.base-url=https://api.g2bulk.com
g2bulk.api-key=c3273f0a06be402b8c38b4410a5328a2e13b304c5ed7c4af45d084ac0b144607